// flow-typed signature: b20a5f228de2a6e1b869a8992f995d18
// flow-typed version: <<STUB>>/timestring_v^5.0.1/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'timestring'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'timestring' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'timestring/index' {
  declare module.exports: $Exports<'timestring'>;
}
declare module 'timestring/index.js' {
  declare module.exports: $Exports<'timestring'>;
}
